

      - name: Show Flutter SDK location
        run: |
          echo "FLUTTER PATHS:"
          find /opt/hostedtoolcache -maxdepth 4 -type d -name "flutter" || true

      - name: Show Android SDK location
        run: |
          echo "ANDROID PATHS:"
          echo "ANDROID_HOME is: $ANDROID_HOME"
          find /usr/local/lib/android -maxdepth 4 -type d || true

      - name: Show Gradle cache
        run: |
          echo "GRADLE PATHS:"
          find /home/runner/ -maxdepth 3 -type d -name ".gradle" || true

      - name: Show Pub cache
        run: |
          echo "PUB PATHS:"
          find /home/runner/ -maxdepth 3 -type d -name ".pub-cache" || true

