name: Build Flutter Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'

      - name: Flutter pub get
        run: flutter pub get

      - name: Fix Android SDK (install cmdline-tools manually)
        run: |
          mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest
          cd /usr/local/lib/android/sdk/cmdline-tools/latest
          curl -L -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip sdk.zip
          rm sdk.zip

      - name: Install Android packages required
        run: |
          yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --install \
            "platform-tools" \
            "build-tools;34.0.0" \
            "platforms;android-33" \
            "platforms;android-34" \
            "ndk;27.0.12077973" \
            "cmake;3.22.1"

      - name: Build APK
        run: flutter build apk --release


 
      - name: Stream and Split Android SDK
        run: |
          sudo tar -C /usr/local/lib/android -cf - sdk | split -b 500m - android-sdk.tar.part-

      - name: Upload Android SDK Parts
        uses: actions/upload-artifact@v4
        with:
          name: android-sdk
          path: android-sdk.tar.part-*
      # ------------------------------
      # EXPORTAR TODO PARA DESCARGA
      # ------------------------------

      - name: Export Android SDK
        uses: actions/upload-artifact@v4
        with:
          name: android-sdk
          path: /usr/local/lib/android/sdk

      - name: Export Gradle Cache
        uses: actions/upload-artifact@v4
        with:
          name: gradle-cache
          path: /home/runner/.gradle

      - name: Export Pub Cache
        uses: actions/upload-artifact@v4
        with:
          name: pub-cache
          path: /home/runner/.pub-cache

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

